/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IIdRouteImport } from './routes/i.$id'
import { Route as EditEditIdRouteImport } from './routes/edit.$editId'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IIdRoute = IIdRouteImport.update({
  id: '/i/$id',
  path: '/i/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditEditIdRoute = EditEditIdRouteImport.update({
  id: '/edit/$editId',
  path: '/edit/$editId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/edit/$editId': typeof EditEditIdRoute
  '/i/$id': typeof IIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/edit/$editId': typeof EditEditIdRoute
  '/i/$id': typeof IIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/edit/$editId': typeof EditEditIdRoute
  '/i/$id': typeof IIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/edit/$editId' | '/i/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/edit/$editId' | '/i/$id'
  id: '__root__' | '/' | '/new' | '/edit/$editId' | '/i/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  EditEditIdRoute: typeof EditEditIdRoute
  IIdRoute: typeof IIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$id': {
      id: '/i/$id'
      path: '/i/$id'
      fullPath: '/i/$id'
      preLoaderRoute: typeof IIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$editId': {
      id: '/edit/$editId'
      path: '/edit/$editId'
      fullPath: '/edit/$editId'
      preLoaderRoute: typeof EditEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  EditEditIdRoute: EditEditIdRoute,
  IIdRoute: IIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
